In [17]:
import numpy as np
import pandas as pd

In [2]:
# random seed
np.random.seed(42)

set1no = 900
set2no = 100

In [22]:
df1 = pd.DataFrame({
    "feature_1": np.random.normal(loc=0, scale=1, size=set1no),
    "feature_2": np.random.normal(loc=0, scale=1, size=set1no),
    "target": [0] * set1no
})

df2 = pd.DataFrame({
    "feature_1": np.random.normal(loc=0, scale=1, size=set2no),
    "feature_2": np.random.normal(loc=0, scale=1, size=set2no),
    "target": [1] * set2no
})

In [23]:
df1.head()

   feature_1  feature_2  target
0  -1.907808  -0.556119       0
1  -0.860385  -0.130060       0
2  -0.413606   1.669070       0
3   1.887688  -0.942558       0
4   0.556553   1.614779       0

In [24]:
df2.head()

   feature_1  feature_2  target
0   0.507020  -0.391877       1
1  -0.057395  -1.017764       1
2  -1.395449  -1.027404       1
3  -0.707911  -0.373268       1
4  -0.262747   0.644518       1

In [25]:
df = pd.concat([df1, df2]).reset_index(drop= True)

In [26]:
df["target"].unique()

array([0, 1])

In [27]:
df["target"].value_counts()

target
0    900
1    100
Name: count, dtype: int64

##### Upsampling ve Downsampling nedir?

--Bu iki yöntem, dengesiz veri setlerinde kullanılan bir yöntemdir. 

--Dengesiz veri seti: hedef değişkende bir sınıfın diğerinden daha çok veya daha az olmasıdır.

##### Downsampling <p>
Çoğunluk sınıfını azaltma işlemidir. Modelin sürekli olarak büyük sınıfı görmesi engellenir ve dengeli bakması sağlanır. <p>

**Avantajları<p>
--Çok basit ve hızlıdır. <p>
--Eğitim süresini azaltır. <p>
--Büyük veri setlerinde kullanılabilir. <p>
--Overfitting riski upsampling'e göre daha düşüktür. <p>

**Dezavantajları <p>
--Veri kaybı <p>
--Önemli gözlemler atılabilir <p>
--Modelin genelleme gücü düşer, veri azsa bilgi kaybı oluşur. <p>

**Ne zaman tercih edilmeli? <p>
--Majority class çok büyük ise <p>
--Veri setin çok geniş ise <p>
--Azınlık sınıf makul sayıda örnek içeriyorsa <p>
    --Örneğin 5 mio'luk bir datasette, 100k minority var ise, majorityi aşağı çekmek mantıklıdır. <p>

##### Upsampling <p>
--Azınlık sınıfındaki gözlem sayısını arttırma işlemidir <p> 
--En basit yöntemi, azınlık sınıfındaki kayıtlar kopyalanır.<p>

**Avantajları <p>
--Veri kaybı olmaz <p>
--Minority class daha görünür hale gelir <p>
--Küçük veri setlerinde faydalıdır. <p>
--Uygulanması kolaydır <p>

**Dezavantajları <p>
--Minority class çok az ise<p>
--Veri kaybetmek istemiyorsan <p>

In [31]:
df_minority = df[df["target"] == 1]
df_majority = df[df["target"] == 0]

In [32]:
from sklearn.utils import resample

In [33]:
df_minortiy_upsample = resample(df_minority, replace= True, n_samples=len(df_majority), random_state=42)

In [34]:
df_minortiy_upsample.shape

(900, 3)

In [35]:
df_upsampled = pd.concat([df_majority, df_minortiy_upsample])

In [36]:
df_upsampled["target"].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [38]:
df_majortiy_downsample = resample(df_majority, replace= True, n_samples=len(df_minority), random_state=42)

In [ ]:
df_majortiy_downsample["target"].value_counts()

target
0    100
Name: count, dtype: int64

In [41]:
df_downsampled = pd.concat([df_majortiy_downsample, df_minority])

In [42]:
df_downsampled["target"].value_counts()

target
0    100
1    100
Name: count, dtype: int64