In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

In [ ]:
""" 
🚀 Genel Roadmap (aklında net olsun)

ML’e hazırlık pipeline’ı şu sırayla olmalı:

1. Data Understanding
shape
column types
null değerler
target ne?
2. Data Cleaning
hatalı değerler (ör: “1M”, “Free”, “$4.99”)
type conversion
outlier kontrolü
3. Balancing (target’a bağlı)
class distribution
gerekiyorsa SMOTE vs
4. Encoding
categorical → numeric
5. EDA
ilişkiler
feature importance hissiyatı

"""

In [ ]:
""" 
🧠 CASE 1 — DATASETİ TANIMA

İlk olarak senden şunu istiyorum:

🎯 Görev:

Dataseti yükle ve aşağıdakileri çıkar:

shape
columns
info()
describe()
null değer analizi

"""

In [2]:
df = pd.read_csv("17-googleplaystore.csv")

In [3]:
df.shape

(10841, 13)

In [11]:
df.head(3)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up

In [4]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [7]:
df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [9]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [12]:
### Kolonların Numeric Hale Getirilmesi

In [23]:
#Size

df_test = df.copy()

In [67]:
df_test["Size"].unique()

array(['19000000', '14000000', '8.7000000', '25000000', '2.8000000',
       '5.6000000', '29000000', '33000000', '3.1000000', '28000000',
       '12000000', '20000000', '21000000', '37000000', '2.7000000',
       '5.5000000', '17000000', '39000000', '31000000', '4.2000000',
       '7.0000000', '23000000', '6.0000000', '6.1000000', '4.6000000',
       '9.2000000', '5.2000000', '11000000', '24000000', nan, '9.4000000',
       '15000000', '10000000', '1.2000000', '26000000', '8.0000000',
       '7.9000000', '56000000', '57000000', '35000000', '54000000', '201',
       '3.6000000', '5.7000000', '8.6000000', '2.4000000', '27000000',
       '2.5000000', '16000000', '3.4000000', '8.9000000', '3.9000000',
       '2.9000000', '38000000', '32000000', '5.4000000', '18000000',
       '1.1000000', '2.2000000', '4.5000000', '9.8000000', '52000000',
       '9.0000000', '6.7000000', '30000000', '2.6000000', '7.1000000',
       '3.7000000', '22000000', '7.4000000', '6.4000000', '3.2000000',
       '8.2000000', '9.9000000', '4.9000000', '9.5000000', '5.0000000',
       '5.9000000', '13000000', '73000000', '6.8000000', '3.5000000',
       '4.0000000', '2.3000000', '7.2000000', '2.1000000', '42000000',
       '7.3000000', '9.1000000', '55000000', '23', '6.5000000',
       '1.5000000', '7.5000000', '51000000', '41000000', '48000000',
       '8.5000000', '46000000', '8.3000000', '4.3000000', '4.7000000',
       '3.3000000', '40000000', '7.8000000', '8.8000000', '6.6000000',
       '5.1000000', '61000000', '66000000', '79', '8.4000000', '118',
       '44000000', '695', '1.6000000', '6.2000000', '18', '53000000',
       '1.4000000', '3.0000000', '5.8000000', '3.8000000', '9.6000000',
       '45000000', '63000000', '49000000', '77000000', '4.4000000',
       '4.8000000', '70000000', '6.9000000', '9.3000000', '10.0000000',
       '8.1000000', '36000000', '84000000', '97000000', '2.0000000',
       '1.9000000', '1.8000000', '5.3000000', '47000000', '556', '526',
       '76000000', '7.6000000', '59000000', '9.7000000', '78000000',
       '72000000', '43000000', '7.7000000', '6.3000000', '334',
       '34000000', '93000000', '65000000', '79000000', '100000000',
       '58000000', '50000000', '68000000', '64000000', '67000000',
       '60000000', '94000000', '232', '99000000', '624', '95000000',
       '8.5', '41', '292', '11', '80000000', '1.7000000', '74000000',
       '62000000', '69000000', '75000000', '98000000', '85000000',
       '82000000', '96000000', '87000000', '71000000', '86000000',
       '91000000', '81000000', '92000000', '83000000', '88000000', '704',
       '862', '899', '378', '266', '375', '1.3000000', '975', '980',
       '4.1000000', '89000000', '696', '544', '525', '920', '779', '853',
       '720', '713', '772', '318', '58', '241', '196', '857', '51', '953',
       '865', '251', '930', '540', '313', '746', '203', '26', '314',
       '239', '371', '220', '730', '756', '91', '293', '17', '74', '14',
       '317', '78', '924', '902', '818', '81', '939', '169', '45', '475',
       '965', '90000000', '545', '61', '283', '655', '714', '93', '872',
       '121', '322', '1.0000000', '976', '172', '238', '549', '206',
       '954', '444', '717', '210', '609', '308', '705', '306', '904',
       '473', '175', '350', '383', '454', '421', '70', '812', '442',
       '842', '417', '412', '459', '478', '335', '782', '721', '430',
       '429', '192', '200', '460', '728', '496', '816', '414', '506',
       '887', '613', '243', '569', '778', '683', '592', '319', '186',
       '840', '647', '191', '373', '437', '598', '716', '585', '982',
       '222', '219', '55', '948', '323', '691', '511', '951', '963', '25',
       '554', '351', '27', '82', '208', '913', '514', '551', '29', '103',
       '898', '743', '116', '153', '209', '353', '499', '173', '597',
       '809', '122', '411', '400', '801', '787', '237', '50', '643',
       '986', '97', '516', '837', '780', '961', '269', '20', '498', '600',
       '749', '642', '881', '72', '656', '601', '221', '228', '108',
       '940', '176', '33', '663', '34', '942', '259', '164', '458', '245',
       '629', '28', '288', '775', '785', '636', '916', '994', '309',
       '485', '914', '903', '608', '500', '54', '562', '847', '957',
       '688', '811', '270', '48', '329', '523', '921', '874', '981',
       '784', '280', '24', '518', '754', '892', '154', '860', '364',
       '387', '626', '161', '879', '39', '970', '170', '141', '160',
       '144', '143', '190', '376', '193', '246', '73', '658', '992',
       '253', '420', '404', '1,000+', '470', '226', '240', '89', '234',
       '257', '861', '467', '157', '44', '676', '67', '552', '885',
       '1020', '582', '619'], dtype=object)

In [40]:
df_test["Size"]= df_test["Size"].str.replace('M', '000000')
df_test["Size"]= df_test["Size"].str.replace('k', '')

In [64]:
df_test["Size"] = df_test["Size"].replace("Varies with device", np.nan)

In [71]:
df_test[df_test["Size"] == "1,000+"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [73]:
df_test = df_test.drop(index = 10472)

In [75]:
df_test["Size"] = df_test["Size"].astype(float)

In [83]:
df_test["Size"] = df_test["Size"] * 1_000_000

In [84]:
df_test["Size"].unique()

array([1.90e+07, 1.40e+07, 8.70e+00, 2.50e+07, 2.80e+00, 5.60e+00,
       2.90e+07, 3.30e+07, 3.10e+00, 2.80e+07, 1.20e+07, 2.00e+07,
       2.10e+07, 3.70e+07, 2.70e+00, 5.50e+00, 1.70e+07, 3.90e+07,
       3.10e+07, 4.20e+00, 7.00e+00, 2.30e+07, 6.00e+00, 6.10e+00,
       4.60e+00, 9.20e+00, 5.20e+00, 1.10e+07, 2.40e+07,      nan,
       9.40e+00, 1.50e+07, 1.00e+07, 1.20e+00, 2.60e+07, 8.00e+00,
       7.90e+00, 5.60e+07, 5.70e+07, 3.50e+07, 5.40e+07, 2.01e+02,
       3.60e+00, 5.70e+00, 8.60e+00, 2.40e+00, 2.70e+07, 2.50e+00,
       1.60e+07, 3.40e+00, 8.90e+00, 3.90e+00, 2.90e+00, 3.80e+07,
       3.20e+07, 5.40e+00, 1.80e+07, 1.10e+00, 2.20e+00, 4.50e+00,
       9.80e+00, 5.20e+07, 9.00e+00, 6.70e+00, 3.00e+07, 2.60e+00,
       7.10e+00, 3.70e+00, 2.20e+07, 7.40e+00, 6.40e+00, 3.20e+00,
       8.20e+00, 9.90e+00, 4.90e+00, 9.50e+00, 5.00e+00, 5.90e+00,
       1.30e+07, 7.30e+07, 6.80e+00, 3.50e+00, 4.00e+00, 2.30e+00,
       7.20e+00, 2.10e+00, 4.20e+07, 7.30e+00, 9.10e+00, 5.50e+07,
       2.30e+01, 6.50e+00, 1.50e+00, 7.50e+00, 5.10e+07, 4.10e+07,
       4.80e+07, 8.50e+00, 4.60e+07, 8.30e+00, 4.30e+00, 4.70e+00,
       3.30e+00, 4.00e+07, 7.80e+00, 8.80e+00, 6.60e+00, 5.10e+00,
       6.10e+07, 6.60e+07, 7.90e+01, 8.40e+00, 1.18e+02, 4.40e+07,
       6.95e+02, 1.60e+00, 6.20e+00, 1.80e+01, 5.30e+07, 1.40e+00,
       3.00e+00, 5.80e+00, 3.80e+00, 9.60e+00, 4.50e+07, 6.30e+07,
       4.90e+07, 7.70e+07, 4.40e+00, 4.80e+00, 7.00e+07, 6.90e+00,
       9.30e+00, 1.00e+01, 8.10e+00, 3.60e+07, 8.40e+07, 9.70e+07,
       2.00e+00, 1.90e+00, 1.80e+00, 5.30e+00, 4.70e+07, 5.56e+02,
       5.26e+02, 7.60e+07, 7.60e+00, 5.90e+07, 9.70e+00, 7.80e+07,
       7.20e+07, 4.30e+07, 7.70e+00, 6.30e+00, 3.34e+02, 3.40e+07,
       9.30e+07, 6.50e+07, 7.90e+07, 1.00e+08, 5.80e+07, 5.00e+07,
       6.80e+07, 6.40e+07, 6.70e+07, 6.00e+07, 9.40e+07, 2.32e+02,
       9.90e+07, 6.24e+02, 9.50e+07, 4.10e+01, 2.92e+02, 1.10e+01,
       8.00e+07, 1.70e+00, 7.40e+07, 6.20e+07, 6.90e+07, 7.50e+07,
       9.80e+07, 8.50e+07, 8.20e+07, 9.60e+07, 8.70e+07, 7.10e+07,
       8.60e+07, 9.10e+07, 8.10e+07, 9.20e+07, 8.30e+07, 8.80e+07,
       7.04e+02, 8.62e+02, 8.99e+02, 3.78e+02, 2.66e+02, 3.75e+02,
       1.30e+00, 9.75e+02, 9.80e+02, 4.10e+00, 8.90e+07, 6.96e+02,
       5.44e+02, 5.25e+02, 9.20e+02, 7.79e+02, 8.53e+02, 7.20e+02,
       7.13e+02, 7.72e+02, 3.18e+02, 5.80e+01, 2.41e+02, 1.96e+02,
       8.57e+02, 5.10e+01, 9.53e+02, 8.65e+02, 2.51e+02, 9.30e+02,
       5.40e+02, 3.13e+02, 7.46e+02, 2.03e+02, 2.60e+01, 3.14e+02,
       2.39e+02, 3.71e+02, 2.20e+02, 7.30e+02, 7.56e+02, 9.10e+01,
       2.93e+02, 1.70e+01, 7.40e+01, 1.40e+01, 3.17e+02, 7.80e+01,
       9.24e+02, 9.02e+02, 8.18e+02, 8.10e+01, 9.39e+02, 1.69e+02,
       4.50e+01, 4.75e+02, 9.65e+02, 9.00e+07, 5.45e+02, 6.10e+01,
       2.83e+02, 6.55e+02, 7.14e+02, 9.30e+01, 8.72e+02, 1.21e+02,
       3.22e+02, 1.00e+00, 9.76e+02, 1.72e+02, 2.38e+02, 5.49e+02,
       2.06e+02, 9.54e+02, 4.44e+02, 7.17e+02, 2.10e+02, 6.09e+02,
       3.08e+02, 7.05e+02, 3.06e+02, 9.04e+02, 4.73e+02, 1.75e+02,
       3.50e+02, 3.83e+02, 4.54e+02, 4.21e+02, 7.00e+01, 8.12e+02,
       4.42e+02, 8.42e+02, 4.17e+02, 4.12e+02, 4.59e+02, 4.78e+02,
       3.35e+02, 7.82e+02, 7.21e+02, 4.30e+02, 4.29e+02, 1.92e+02,
       2.00e+02, 4.60e+02, 7.28e+02, 4.96e+02, 8.16e+02, 4.14e+02,
       5.06e+02, 8.87e+02, 6.13e+02, 2.43e+02, 5.69e+02, 7.78e+02,
       6.83e+02, 5.92e+02, 3.19e+02, 1.86e+02, 8.40e+02, 6.47e+02,
       1.91e+02, 3.73e+02, 4.37e+02, 5.98e+02, 7.16e+02, 5.85e+02,
       9.82e+02, 2.22e+02, 2.19e+02, 5.50e+01, 9.48e+02, 3.23e+02,
       6.91e+02, 5.11e+02, 9.51e+02, 9.63e+02, 2.50e+01, 5.54e+02,
       3.51e+02, 2.70e+01, 8.20e+01, 2.08e+02, 9.13e+02, 5.14e+02,
       5.51e+02, 2.90e+01, 1.03e+02, 8.98e+02, 7.43e+02, 1.16e+02,
       1.53e+02, 2.09e+02, 3.53e+02, 4.99e+02, 1.73e+02, 5.97e+02,
       8.09e+02, 1.22e+02, 4.11e+02, 4.00e+02, 8.01e+02, 7.87e+02,
       2.37e+02, 5.00e+01, 6.43e+02, 9.86e+02, 9.70e+01, 5.16e+02,
       8.37e+02, 7.80e+02, 9.61e+02, 2.69e+02, 2.00e+01, 4.98e+02,
       6.00e+02, 7.49e+02, 6.42e+02, 8.81e+02, 7.20e+01, 6.56e+02,
       6.01e+02, 2.21e+02, 2.28e+02, 1.08e+02, 9.40e+02, 1.76e+02,
       3.30e+01, 6.63e+02, 3.40e+01, 9.42e+02, 2.59e+02, 1.64e+02,
       4.58e+02, 2.45e+02, 6.29e+02, 2.80e+01, 2.88e+02, 7.75e+02,
       7.85e+02, 6.36e+02, 9.16e+02, 9.94e+02, 3.09e+02, 4.85e+02,
       9.14e+02, 9.03e+02, 6.08e+02, 5.00e+02, 5.40e+01, 5.62e+02,
       8.47e+02, 9.57e+02, 6.88e+02, 8.11e+02, 2.70e+02, 4.80e+01,
       3.29e+02, 5.23e+02, 9.21e+02, 8.74e+02, 9.81e+02, 7.84e+02,
       2.80e+02, 2.40e+01, 5.18e+02, 7.54e+02, 8.92e+02, 1.54e+02,
       8.60e+02, 3.64e+02, 3.87e+02, 6.26e+02, 1.61e+02, 8.79e+02,
       3.90e+01, 9.70e+02, 1.70e+02, 1.41e+02, 1.60e+02, 1.44e+02,
       1.43e+02, 1.90e+02, 3.76e+02, 1.93e+02, 2.46e+02, 7.30e+01,
       6.58e+02, 9.92e+02, 2.53e+02, 4.20e+02, 4.04e+02, 4.70e+02,
       2.26e+02, 2.40e+02, 8.90e+01, 2.34e+02, 2.57e+02, 8.61e+02,
       4.67e+02, 1.57e+02, 4.40e+01, 6.76e+02, 6.70e+01, 5.52e+02,
       8.85e+02, 1.02e+03, 5.82e+02, 6.19e+02])

In [86]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  object
 1   Category        10840 non-null  object
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  object
 4   Size            9145 non-null   float64
 5   Installs        10840 non-null  object
 6   Type            10839 non-null  object
 7   Price           10840 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10840 non-null  object
 11  Current Ver     10832 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(2), object(11)
memory usage: 1.2+ MB